name: build-verification

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set Version
        run: echo VERSION=`git describe --tags --always` >> $GITHUB_ENV

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./build
          file: ./build/Dockerfile
          push: false
          load: true
          platforms: |
            linux/amd64
          build-args: |
            VERSION=${{ env.VERSION }}
          tags: |
            airqj/openvpn:latest
            airqj/openvpn:${{ env.VERSION }}

      - name: Export Docker image
        run: |
          docker save airqj/openvpn:${{ env.VERSION }} | gzip > airqj-openvpn-${{ env.VERSION }}.tar.gz
          ls -lh airqj-openvpn-${{ env.VERSION }}.tar.gz

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: airqj-openvpn-docker-image-${{ env.VERSION }}
          path: airqj-openvpn-${{ env.VERSION }}.tar.gz
          retention-days: 30